plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
}

group = 'DoodieMan'
version = '1.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'spigot-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }
    maven {
        name = 'CodeMC'
        url = 'https://repo.codemc.io/repository/maven-public/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot:1.8.8-R0.1-SNAPSHOT'
    implementation 'de.tr7zw:item-nbt-api:2.16.0'
    compileOnly 'org.projectlombok:lombok:1.18.24'
    annotationProcessor 'org.projectlombok:lombok:1.18.24'
}

shadowJar {
    archiveClassifier.set('')
    relocate('de.tr7zw.changeme.nbtapi', 'doodieman.posemaster.libs.nbtapi')
}

build {
    dependsOn(shadowJar)
}

processResources {
    expand('project': project)
}
