name: PoseMaster
version: '${project.version}'
main: doodieman.posemaster.PoseMaster
authors: [DoodieMan]
description: The plugin to change armorstand positions to your liking!
commands:
  posemaster:
    aliases: [posem, pose, pmaster]
    permission: "posemaster.admin"
    permission-message: "§cYou do not have access to this command!"